# Useful extensions and outlook {#ExtOutlook}

This last chapter is dedicated to possible future applications of `SPI-IPM`. For now, it is simply a collection of section titles alluding to potentially useful and interesting extensions of the model focusing on accommodating other species and additional data sources, as well as building further on the potential of multi-population studies. 
The collection of section titles may serve as inspiration, but ideally, future users of `SPI-IPM` will contribute and describe their model extensions in this chapter. 

##	Adapting the population model for your species/population

###	Accounting for multiple broods per bird per year

###	Altering age structure

###	Individual heterogeneity beyond age: sex, traits, and more


##	Including additional data and informative priors

###	Including partially observed age information

###	Making the most of auxiliary knowledge about immigrants/dispersers

###	Letting published values help with estimation when data is sparse


##	Building on the multi-population perspective

###	Joint analysis of data from several populations

###	Modelling cross-population covariation

###	Estimating hyper-parameters in large-scale analyses

###	Unlocking the secrets of dispersal

